version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - ./dev:/var/www
    working_dir: /var/www
    command: ["php-fpm"]
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mariadb:10
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dynamice
      MYSQL_USER: su
      MYSQL_PASSWORD: suadmin
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

  node:
    image: node:18-bullseye
    container_name: node
    working_dir: /var/www
    command: tail -f /dev/null
    volumes:
      - ./dev:/var/www
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
